// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class FACTURAS
{
    public int ID_FACTURA { get; set; }

    public DateTime FECHA { get; set; }

    public int ID_PASAJERO { get; set; }

    public int ID_PAGO { get; set; }

    public int ID_TIPO_PAGO { get; set; }

    public virtual ICollection<CONCESIONES> CONCESIONES { get; set; } = new List<CONCESIONES>();

    public virtual ICollection<DETALLE_FACTURA> DETALLE_FACTURA { get; set; } = new List<DETALLE_FACTURA>();

    public virtual PAGOS ID_PAGO1 { get; set; }

    public virtual MEDIOS_DE_PAGO ID_PAGONavigation { get; set; }

    public virtual CLIENTES ID_PASAJERONavigation { get; set; }
}