// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class Gasto_Promedio_Cliente
{
    public int ID_PASAJERO { get; set; }

    public string nombre { get; set; }

    public string apellido { get; set; }

    public decimal? gasto_promedio { get; set; }
}