// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class PROMOCIONES
{
    public int ID_PROMO { get; set; }

    public string DESCRIPCION { get; set; }

    public DateOnly? INICIO { get; set; }

    public DateOnly? FIN { get; set; }

    public decimal? DESCUENTO { get; set; }

    public virtual ICollection<PROMOCIONES_VUELOS> PROMOCIONES_VUELOS { get; set; } = new List<PROMOCIONES_VUELOS>();
}