// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class PROMOCIONES_VUELOS
{
    public int ID_PROMO_VUELO { get; set; }

    public int ID_PROMO { get; set; }

    public int ID_VUELO { get; set; }

    public virtual PROMOCIONES ID_PROMONavigation { get; set; }

    public virtual VUELOS ID_VUELONavigation { get; set; }
}