// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class Rutas_Rentables
{
    public string origen { get; set; }

    public string destino { get; set; }

    public int? anio { get; set; }

    public int? mes { get; set; }

    public decimal? margen_total { get; set; }
}