// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class vw_DestinosImproductivos
{
    public int id_destino { get; set; }

    public string nombre_destino { get; set; }

    public decimal? promedio_ocupacion { get; set; }
}