// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class vw_precio_ocupacion
{
    public int id_vuelo { get; set; }

    public decimal? porcentaje_ocupacion { get; set; }

    public decimal PRECIO_BASE_VUELO { get; set; }

    public decimal? incremento { get; set; }

    public decimal? precio_final { get; set; }
}