// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Wappirepasoparcial.Models;

public partial class AEROLINEASContext : DbContext
{
    public AEROLINEASContext(DbContextOptions<AEROLINEASContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AEROPUERTOS> AEROPUERTOS { get; set; }

    public virtual DbSet<ASIENTOS> ASIENTOS { get; set; }

    public virtual DbSet<AVIONES> AVIONES { get; set; }

    public virtual DbSet<CLIENTES> CLIENTES { get; set; }

    public virtual DbSet<CONCESIONES> CONCESIONES { get; set; }

    public virtual DbSet<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }

    public virtual DbSet<DETALLE_VUELOS> DETALLE_VUELOS { get; set; }

    public virtual DbSet<EQUIPAJE> EQUIPAJE { get; set; }

    public virtual DbSet<FACTURAS> FACTURAS { get; set; }

    public virtual DbSet<MEDIOS_DE_PAGO> MEDIOS_DE_PAGO { get; set; }

    public virtual DbSet<PAGOS> PAGOS { get; set; }

    public virtual DbSet<PAISES> PAISES { get; set; }

    public virtual DbSet<PROMOCIONES> PROMOCIONES { get; set; }

    public virtual DbSet<PROMOCIONES_VUELOS> PROMOCIONES_VUELOS { get; set; }

    public virtual DbSet<PROVINCIAS> PROVINCIAS { get; set; }

    public virtual DbSet<TIPOS_CLIENTES> TIPOS_CLIENTES { get; set; }

    public virtual DbSet<TIPO_ASIENTOS> TIPO_ASIENTOS { get; set; }

    public virtual DbSet<TIPO_DOCUMENTOS> TIPO_DOCUMENTOS { get; set; }

    public virtual DbSet<TIPO_EQUIPAJE> TIPO_EQUIPAJE { get; set; }

    public virtual DbSet<VUELOS> VUELOS { get; set; }

    public virtual DbSet<vw_recuperar_pasajero> vw_recuperar_pasajero { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AEROPUERTOS>(entity =>
        {
            entity.HasKey(e => e.ID_AEROPUERTO);

            entity.Property(e => e.NOMBRE)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_PROVINCIANavigation).WithMany(p => p.AEROPUERTOS)
                .HasForeignKey(d => d.ID_PROVINCIA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AEROPUERTOS_PROVINCIA");
        });

        modelBuilder.Entity<ASIENTOS>(entity =>
        {
            entity.HasKey(e => e.ID_ASIENTOS);

            entity.Property(e => e.PRECIO_EXTRA_DECIMAL).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.ID_TIPO_ASIENTONavigation).WithMany(p => p.ASIENTOS)
                .HasForeignKey(d => d.ID_TIPO_ASIENTO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ASIENTOS_TIPO_ASIENTOS");

            entity.HasOne(d => d.ID_VUELONavigation).WithMany(p => p.ASIENTOS)
                .HasForeignKey(d => d.ID_VUELO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ASIENTOS_VUELOS");
        });

        modelBuilder.Entity<AVIONES>(entity =>
        {
            entity.HasKey(e => e.ID_AVION);

            entity.Property(e => e.NOMBRE_AVION)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.STATUS_VUELO)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_AEROPUERTONavigation).WithMany(p => p.AVIONES)
                .HasForeignKey(d => d.ID_AEROPUERTO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AVIONES_AEROPUERTOS");
        });

        modelBuilder.Entity<CLIENTES>(entity =>
        {
            entity.HasKey(e => e.ID_PASAJERO);

            entity.HasIndex(e => e.NRO_DOC, "UQ__CLIENTES__EAF90E97482A2B02").IsUnique();

            entity.Property(e => e.APELLIDO)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CALLE)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EMAIL)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.NOMBRE)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TELEFONO)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_PROVINCIANavigation).WithMany(p => p.CLIENTES)
                .HasForeignKey(d => d.ID_PROVINCIA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CLIENTES_PROVINCIAS");

            entity.HasOne(d => d.ID_TIPO_CLIENTENavigation).WithMany(p => p.CLIENTES)
                .HasForeignKey(d => d.ID_TIPO_CLIENTE)
                .HasConstraintName("FK_CLIENTES_TIPO");

            entity.HasOne(d => d.ID_TIPO_DOCNavigation).WithMany(p => p.CLIENTES)
                .HasForeignKey(d => d.ID_TIPO_DOC)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CLIENTES_TIPO_DOCUMENTOS");
        });

        modelBuilder.Entity<CONCESIONES>(entity =>
        {
            entity.HasKey(e => e.ID_CONCECICION);

            entity.Property(e => e.FECHA_CANCELACION).HasColumnType("datetime");
            entity.Property(e => e.MONTO_REEMBOLSADO).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.MOTIVO)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_FACTURANavigation).WithMany(p => p.CONCESIONES)
                .HasForeignKey(d => d.ID_FACTURA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CONCESIONES_FACTURAS");
        });

        modelBuilder.Entity<DETALLE_FACTURA>(entity =>
        {
            entity.HasKey(e => e.ID_DETALLE_FACTURA);

            entity.Property(e => e.PRECIO).HasColumnType("decimal(15, 4)");

            entity.HasOne(d => d.ID_DETALLE_VUELONavigation).WithMany(p => p.DETALLE_FACTURA)
                .HasForeignKey(d => d.ID_DETALLE_VUELO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DETALLE_FACTURA_DETALLE_VUELOS");

            entity.HasOne(d => d.ID_FACTURANavigation).WithMany(p => p.DETALLE_FACTURA)
                .HasForeignKey(d => d.ID_FACTURA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DETALLE_FACTURA_FACTURAS");
        });

        modelBuilder.Entity<DETALLE_VUELOS>(entity =>
        {
            entity.HasKey(e => e.ID_DETALLE_VUELO);

            entity.Property(e => e.FECHA).HasColumnType("datetime");
            entity.Property(e => e.OBSERVACIONES)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.PRECIO_FINAL).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.ID_ASIENTONavigation).WithMany(p => p.DETALLE_VUELOS)
                .HasForeignKey(d => d.ID_ASIENTO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DETALLE_VUELOS_ASIENTOS");

            entity.HasOne(d => d.ID_EQUIP_DETALLENavigation).WithMany(p => p.DETALLE_VUELOS)
                .HasForeignKey(d => d.ID_EQUIP_DETALLE)
                .HasConstraintName("FK_DETALLE_VUELOS_EQUIPAJE");

            entity.HasOne(d => d.ID_PASAJERONavigation).WithMany(p => p.DETALLE_VUELOS)
                .HasForeignKey(d => d.ID_PASAJERO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DETALLE_VUELOS_CLIENTES");

            entity.HasOne(d => d.ID_VUELONavigation).WithMany(p => p.DETALLE_VUELOS)
                .HasForeignKey(d => d.ID_VUELO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DETALLE_VUELOS_VUELOS");
        });

        modelBuilder.Entity<EQUIPAJE>(entity =>
        {
            entity.HasKey(e => e.ID_EQUIPAJE);

            entity.Property(e => e.PRECIO).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.TIPO_EQUIPAJENavigation).WithMany(p => p.EQUIPAJE)
                .HasForeignKey(d => d.TIPO_EQUIPAJE)
                .HasConstraintName("FK_EQUIPAJE_TIPO_EQUIPAJE");
        });

        modelBuilder.Entity<FACTURAS>(entity =>
        {
            entity.HasKey(e => e.ID_FACTURA);

            entity.Property(e => e.FECHA).HasColumnType("datetime");

            entity.HasOne(d => d.ID_PAGONavigation).WithMany(p => p.FACTURAS)
                .HasForeignKey(d => d.ID_PAGO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FACTURAS_TIPO_PAGO");

            entity.HasOne(d => d.ID_PAGO1).WithMany(p => p.FACTURAS)
                .HasForeignKey(d => d.ID_PAGO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FACTURAS_PAGOS");

            entity.HasOne(d => d.ID_PASAJERONavigation).WithMany(p => p.FACTURAS)
                .HasForeignKey(d => d.ID_PASAJERO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FACTURAS_CLIENTES");
        });

        modelBuilder.Entity<MEDIOS_DE_PAGO>(entity =>
        {
            entity.HasKey(e => e.ID_MEDIO_PAGO).HasName("PK_MEDIO_PAGO");

            entity.Property(e => e.MEDIO_PAGO)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PAGOS>(entity =>
        {
            entity.HasKey(e => e.ID_PAGO);

            entity.Property(e => e.FECHA).HasColumnType("datetime");
            entity.Property(e => e.MONTO).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.ID_MEDIO_PAGONavigation).WithMany(p => p.PAGOS)
                .HasForeignKey(d => d.ID_MEDIO_PAGO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PAGOS_MEDIOS_PAGOS");
        });

        modelBuilder.Entity<PAISES>(entity =>
        {
            entity.HasKey(e => e.ID_PAIS);

            entity.Property(e => e.NOMBRE)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PROMOCIONES>(entity =>
        {
            entity.HasKey(e => e.ID_PROMO);

            entity.Property(e => e.DESCRIPCION)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.DESCUENTO).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<PROMOCIONES_VUELOS>(entity =>
        {
            entity.HasKey(e => e.ID_PROMO_VUELO);

            entity.HasOne(d => d.ID_PROMONavigation).WithMany(p => p.PROMOCIONES_VUELOS)
                .HasForeignKey(d => d.ID_PROMO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PROMO_VUELOS_PROMOCIONES");

            entity.HasOne(d => d.ID_VUELONavigation).WithMany(p => p.PROMOCIONES_VUELOS)
                .HasForeignKey(d => d.ID_VUELO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PROMO_VUELOS_VUELOS");
        });

        modelBuilder.Entity<PROVINCIAS>(entity =>
        {
            entity.HasKey(e => e.ID_PROVINCIA);

            entity.Property(e => e.NOMBRE)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_PAISNavigation).WithMany(p => p.PROVINCIAS)
                .HasForeignKey(d => d.ID_PAIS)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PROVINCIAS_PAISES");
        });

        modelBuilder.Entity<TIPOS_CLIENTES>(entity =>
        {
            entity.HasKey(e => e.ID_TIPO_CLIENTE).HasName("PK_TIPO_CLIENTE");

            entity.Property(e => e.TIPO_CLIENTE)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TIPO_ASIENTOS>(entity =>
        {
            entity.HasKey(e => e.ID_TIPO_ASIENTO);

            entity.Property(e => e.DESCRIPCION)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.NOMBRE)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.PRECIO_ADD_TIPO_ASIENTO).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<TIPO_DOCUMENTOS>(entity =>
        {
            entity.HasKey(e => e.ID_TIPO_DOC);

            entity.Property(e => e.TIPO_DOC)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TIPO_EQUIPAJE>(entity =>
        {
            entity.HasKey(e => e.ID_EQUIPAJE);

            entity.Property(e => e.DESCRIPCION)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<VUELOS>(entity =>
        {
            entity.HasKey(e => e.ID_VUELO);

            entity.Property(e => e.CODIGO_VUELO)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FECHA_LLEGADA).HasColumnType("datetime");
            entity.Property(e => e.FECHA_SALIDA).HasColumnType("datetime");
            entity.Property(e => e.PRECIO_BASE_VUELO).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.ID_AEROPUERTO_ORIGENNavigation).WithMany(p => p.VUELOS)
                .HasForeignKey(d => d.ID_AEROPUERTO_ORIGEN)
                .HasConstraintName("FK_VUELOS_AEROPUERTOS");

            entity.HasOne(d => d.ID_AVIONNavigation).WithMany(p => p.VUELOS)
                .HasForeignKey(d => d.ID_AVION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VUELOS_AVIONES");
        });

        modelBuilder.Entity<vw_recuperar_pasajero>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_recuperar_pasajero");

            entity.Property(e => e.APELLIDO)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EMAIL)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.NOMBRE)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TELEFONO)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.mes_que_más_viaja)
                .HasMaxLength(30)
                .HasColumnName("mes que más viaja");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}