// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class AEROPUERTOS
{
    public int ID_AEROPUERTO { get; set; }

    public string NOMBRE { get; set; }

    public int ID_PROVINCIA { get; set; }

    public virtual ICollection<AVIONES> AVIONES { get; set; } = new List<AVIONES>();

    public virtual PROVINCIAS ID_PROVINCIANavigation { get; set; }

    public virtual ICollection<VUELOS> VUELOS { get; set; } = new List<VUELOS>();
}