// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class ASIENTOS
{
    public int ID_ASIENTOS { get; set; }

    public int NUMERO { get; set; }

    public bool? OCUPADO { get; set; }

    public decimal? PRECIO_EXTRA_DECIMAL { get; set; }

    public int ID_TIPO_ASIENTO { get; set; }

    public int ID_VUELO { get; set; }

    public virtual ICollection<DETALLE_VUELOS> DETALLE_VUELOS { get; set; } = new List<DETALLE_VUELOS>();

    public virtual TIPO_ASIENTOS ID_TIPO_ASIENTONavigation { get; set; }

    public virtual VUELOS ID_VUELONavigation { get; set; }
}