// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class AVIONES
{
    public int ID_AVION { get; set; }

    public string STATUS_VUELO { get; set; }

    public int CAPACIDAD { get; set; }

    public string NOMBRE_AVION { get; set; }

    public int ID_AEROPUERTO { get; set; }

    public virtual AEROPUERTOS ID_AEROPUERTONavigation { get; set; }

    public virtual ICollection<VUELOS> VUELOS { get; set; } = new List<VUELOS>();
}