// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class CLIENTES
{
    public int ID_PASAJERO { get; set; }

    public string NOMBRE { get; set; }

    public string APELLIDO { get; set; }

    public int ID_TIPO_DOC { get; set; }

    public int NRO_DOC { get; set; }

    public int? ID_TIPO_CLIENTE { get; set; }

    public string CALLE { get; set; }

    public string EMAIL { get; set; }

    public string TELEFONO { get; set; }

    public int ID_PROVINCIA { get; set; }

    public virtual ICollection<DETALLE_VUELOS> DETALLE_VUELOS { get; set; } = new List<DETALLE_VUELOS>();

    public virtual ICollection<FACTURAS> FACTURAS { get; set; } = new List<FACTURAS>();

    public virtual PROVINCIAS ID_PROVINCIANavigation { get; set; }

    public virtual TIPOS_CLIENTES ID_TIPO_CLIENTENavigation { get; set; }

    public virtual TIPO_DOCUMENTOS ID_TIPO_DOCNavigation { get; set; }

    public virtual ICollection<USUARIOS> USUARIOS { get; set; } = new List<USUARIOS>();
}