// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class CONCESIONES
{
    public int ID_CONCECICION { get; set; }

    public string MOTIVO { get; set; }

    public decimal? MONTO_REEMBOLSADO { get; set; }

    public DateTime? FECHA_CANCELACION { get; set; }

    public int ID_FACTURA { get; set; }

    public virtual FACTURAS ID_FACTURANavigation { get; set; }
}