// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class DETALLE_FACTURA
{
    public int ID_DETALLE_FACTURA { get; set; }

    public decimal TOTAL { get; set; }

    public int ID_FACTURA { get; set; }

    public int ID_DETALLE_VUELO { get; set; }

    public virtual DETALLE_VUELOS ID_DETALLE_VUELONavigation { get; set; }

    public virtual FACTURAS ID_FACTURANavigation { get; set; }
}