// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class DETALLE_VUELOS
{
    public int ID_DETALLE_VUELO { get; set; }

    public DateTime? FECHA { get; set; }

    public decimal PRECIO_FINAL { get; set; }

    public string OBSERVACIONES { get; set; }

    public int ID_VUELO { get; set; }

    public int ID_PASAJERO { get; set; }

    public int ID_ASIENTO { get; set; }

    public int? ID_EQUIP_DETALLE { get; set; }

    public virtual ICollection<DETALLE_FACTURA> DETALLE_FACTURA { get; set; } = new List<DETALLE_FACTURA>();

    public virtual ASIENTOS ID_ASIENTONavigation { get; set; }

    public virtual EQUIPAJE ID_EQUIP_DETALLENavigation { get; set; }

    public virtual CLIENTES ID_PASAJERONavigation { get; set; }

    public virtual VUELOS ID_VUELONavigation { get; set; }
}