// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class EQUIPAJE
{
    public int ID_EQUIPAJE { get; set; }

    public decimal? PRECIO { get; set; }

    public int? PESO { get; set; }

    public int? TIPO_EQUIPAJE { get; set; }

    public virtual ICollection<DETALLE_VUELOS> DETALLE_VUELOS { get; set; } = new List<DETALLE_VUELOS>();

    public virtual TIPO_EQUIPAJE TIPO_EQUIPAJENavigation { get; set; }
}