// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class MEDIOS_DE_PAGO
{
    public int ID_MEDIO_PAGO { get; set; }

    public string MEDIO_PAGO { get; set; }

    public virtual ICollection<FACTURAS> FACTURAS { get; set; } = new List<FACTURAS>();

    public virtual ICollection<PAGOS> PAGOS { get; set; } = new List<PAGOS>();
}