// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class PAGOS
{
    public int ID_PAGO { get; set; }

    public decimal MONTO { get; set; }

    public DateTime FECHA { get; set; }

    public int ID_MEDIO_PAGO { get; set; }

    public virtual ICollection<FACTURAS> FACTURAS { get; set; } = new List<FACTURAS>();

    public virtual MEDIOS_DE_PAGO ID_MEDIO_PAGONavigation { get; set; }
}