// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class PAISES
{
    public int ID_PAIS { get; set; }

    public string NOMBRE { get; set; }

    public virtual ICollection<PROVINCIAS> PROVINCIAS { get; set; } = new List<PROVINCIAS>();
}