// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class PROVINCIAS
{
    public int ID_PROVINCIA { get; set; }

    public string NOMBRE { get; set; }

    public int ID_PAIS { get; set; }

    public virtual ICollection<AEROPUERTOS> AEROPUERTOS { get; set; } = new List<AEROPUERTOS>();

    public virtual ICollection<CLIENTES> CLIENTES { get; set; } = new List<CLIENTES>();

    public virtual PAISES ID_PAISNavigation { get; set; }
}