// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class TIPO_ASIENTOS
{
    public int ID_TIPO_ASIENTO { get; set; }

    public decimal PRECIO_ADD_TIPO_ASIENTO { get; set; }

    public string NOMBRE { get; set; }

    public string DESCRIPCION { get; set; }

    public virtual ICollection<ASIENTOS> ASIENTOS { get; set; } = new List<ASIENTOS>();
}