// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class TIPO_EQUIPAJE
{
    public int ID_EQUIPAJE { get; set; }

    public string DESCRIPCION { get; set; }

    public virtual ICollection<EQUIPAJE> EQUIPAJE { get; set; } = new List<EQUIPAJE>();
}