// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class TIPO_DOCUMENTOS
{
    public int ID_TIPO_DOC { get; set; }

    public string TIPO_DOC { get; set; }

    public virtual ICollection<CLIENTES> CLIENTES { get; set; } = new List<CLIENTES>();
}