// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class USUARIOS
{
    public int ID_USUARIO { get; set; }

    public string USUARIO { get; set; }

    public string CONTRASEÑA { get; set; }

    public int? ID_PASAJERO { get; set; }

    public virtual CLIENTES ID_PASAJERONavigation { get; set; }
}