// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class VUELOS
{
    public int ID_VUELO { get; set; }

    public string CODIGO_VUELO { get; set; }

    public int? ID_AEROPUERTO_ORIGEN { get; set; }

    public int? ID_AEROPUERTO_DESTINO { get; set; }

    public DateTime FECHA_SALIDA { get; set; }

    public DateTime FECHA_LLEGADA { get; set; }

    public decimal PRECIO_BASE_VUELO { get; set; }

    public int ID_AVION { get; set; }

    public virtual ICollection<ASIENTOS> ASIENTOS { get; set; } = new List<ASIENTOS>();

    public virtual ICollection<DETALLE_VUELOS> DETALLE_VUELOS { get; set; } = new List<DETALLE_VUELOS>();

    public virtual AEROPUERTOS ID_AEROPUERTO_ORIGENNavigation { get; set; }

    public virtual AVIONES ID_AVIONNavigation { get; set; }

    public virtual ICollection<PROMOCIONES_VUELOS> PROMOCIONES_VUELOS { get; set; } = new List<PROMOCIONES_VUELOS>();
}