// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class vw_OcupacionVuelos
{
    public int id_vuelo { get; set; }

    public int id_avion { get; set; }

    public int CAPACIDAD { get; set; }

    public int? asientos_ocupados { get; set; }

    public decimal? porcentaje_ocupacion { get; set; }
}