// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wappirepasoparcial.Models;

public partial class vw_recuperar_pasajero
{
    public int ID_PASAJERO { get; set; }

    public string mes_que_más_viaja { get; set; }

    public int? total_compras_mes { get; set; }

    public string NOMBRE { get; set; }

    public string APELLIDO { get; set; }

    public string EMAIL { get; set; }

    public string TELEFONO { get; set; }
}